backend:
  name: git-gateway
  branch: main
media_folder: "/src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "BlogEn"
    label: "Publicación en inglés"
    folder: "src/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "excerpt", widget: "string"}
      - {label: "Image", name: "featuredImage", widget: "image"}
      - {label: "Small Image", name: "featuredImageMini", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "BlogEs"
    label: "Publicación en español"
    folder: "src/es/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tags", name: "tags", widget: "list", default: ["postEs"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "postEs.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "excerpt", widget: "string"}
      - {label: "Image", name: "featuredImage", widget: "image"}
      - {label: "Small Image", name: "featuredImageMini", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Prueba"
    label: "Categoría en inglés"
    folder: src/blog/categories
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "categorie", name: "categorie", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["categorie"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Image", name: "featuredImage", widget: "image"}

    - name: "Hola"
    label: "Categoría en español"
    folder: src/es/blog/categories
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "categorie", name: "categorie", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["categorieEs"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Image", name: "featuredImage", widget: "image"}
